### ISSUE TITLE
Fix Docker workflow

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#321] opened 2022-04-20 16:59 UTC
[Docker workflow](https://github.com/interledger/rafiki/blob/main/.github/workflows/docker.yml) is failing after merging https://github.com/interledger/rafiki/pull/315 with:
```
UsageError: Couldn't find knex@npm:0.21.19 [aa597] in the currently installed PnP map - running an install might help
```

**Comment by wilsonianb** [comment] 2022-04-20 17:03
I tried updating [@yarnpkg/plugin-docker-build](https://github.com/Dcard/yarn-plugins/tree/master/packages/docker-build) to incorporate https://github.com/Dcard/yarn-plugins/commit/89a71671514b49606b20db52a71a5f3786e92fca but that didn't help.

**Comment by njlie** [comment] 2022-04-21 00:26
Something about `knex` being added to the `auth` workspace causes link between it and `backend` to be displaced somehow. The build only fails if `knex` is included in `auth` at the same version as `backend`. Removing it from `auth` will cause the `backend` build process to succeed again. Not sure why that is.

**Comment by rluckom-coil** [comment] 2022-06-24 12:36
I spent yesterday looking into this.

We use [yarn-plugin-docker-build](https://github.com/Dcard/yarn-plugins/tree/master/packages/docker-build) to do our docker builds. The way that it (is supposed to) work(s) is:

1. [resolve all dependencies](https://github.com/Dcard/yarn-plugins/blob/master/packages/docker-build/src/commands/build.ts#L104)
2. [fetch all dependencies](https://github.com/Dcard/yarn-plugins/blob/master/packages/docker-build/src/commands/build.ts#L108)
3. [Make a temporary directory for doing the docker build](https://github.com/Dcard/yarn-plugins/blob/master/packages/docker-build/src/commands/build.ts#L111)
4. Copy a bunch of stuff to the tempdir, including, importantly [the set of "cache marked files"](https://github.com/Dcard/yarn-plugins/blob/master/packages/docker-build/src/utils/copyCacheMarkedFiles.ts#L15). The ["cache marked files"](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Cache.ts#L32) are "the list of cache files that got accessed since the last time you cleared the variable". In this case, they are all the files that yarn noticed internally while doing `fetchEverything` (I edited the plugin manually to inspect the `cache.markedFiles` variable; the `fetchEverything` step is when it gets populated). The cache marked files do _not_ include the knex library. This implies that it is the yarn `fetchEverything` (or possibly `resolveEverything`) is not correctly fetching (or resolving) everything.

So why are `fetchEverything` and `resolveEverything` not succeeding? Presumably there is either a bug in those functions or else there is a problem with the input they are getting.

The rafiki repo is using yarn zeroinstall, which means that yarn creates a `.pnp.cjs` file that contains a mapping of all the project packages. This file appears to be the only input that really matters during dependency resolution. The `aa597` hash in error we see in our builds--`Couldn't find knex@npm:0.21.19 [aa597]` --refers to the hash of a[ "virtual package"](https://yarnpkg.com/advanced/lexicon/#virtual-package) that [used to contain knex for the backend package](https://github.com/interledger/rafiki/blob/36cd25e13072aefa173e593d227ff3eb99277c81/.pnp.cjs) but no longer does.

So what's wrong with the `.pnp.cjs` file? Unfortunately, I can't really tell, because that file says, right at the top:

```
"This file is automatically generated. Do not touch it, or risk",
      "your modifications being lost. We also recommend you not to read",
      "it either without using the @yarnpkg/pnp package, as the data layout",
      "is entirely unspecified and WILL change from a version to another."
```

Here I broke off the search.


So what are our options?

1. Use different versions of knex in auth vs in backend. If we use different point versions the problem goes away.
2. Do docker builds somewhere other than inside yarn--note that `yarn workspace pack backend` _does_ work, so just making the package isn't broken, just doing it in a plugin. (this admittedly makes it seem like the problem is the plugin's fault, but I looked closely and experimented a lot, and it definitely seems like the yarn internals used by the plugin that are the problem)
3. try to come up with a minimal reproduction, file a yarn bug, stay broken until they fix it.

**Comment by rluckom-coil** [comment] 2022-07-11 12:53
working as of https://github.com/interledger/rafiki/pull/386

**Closed by rluckom-coil** 2022-07-11 12:53 UTC
Labels: type: ci, pkg: backend
