### ISSUE TITLE
Add Open Payments auth server discoverability

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#2045] opened 2023-10-17 13:30 UTC
Currently the incoming/outgoing payment urls are inferred via the URL pattern. An example is the following IP
```
https://ilp.rafiki.money/mattusd/incoming-payments/a4885cd0-2318-468b-9194-4b30787c4ddd
```
Assume a payment pointer URL of `https://ilp.rafiki.money/mattusd`

Removing the coupling does present a problem, in that clients need to know where the auth server is for resources. GNAP has a spec to define [RS first discovery](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol-15#name-rs-first-method-of-as-disco)

**Comment by sabineschaller** [comment] 2023-10-19 09:02
Duplicate of
- https://github.com/interledger/rafiki/issues/1897  ?

I think this is already being worked on by @njlie and @BlairCurrey.

**Comment by mkurapov** [comment] 2023-10-19 13:34
@sabineschaller @njlie @BlairCurrey I think we need a separate issue to "include `resourceUrl` in the wallet address response", right?

**Comment by sabineschaller** [comment] 2023-10-19 13:39
That we do indeed.

**Comment by njlie** [comment] 2023-10-26 21:07
So uh...it looks like we [already implement this](https://github.com/interledger/rafiki/blob/10824e135754916714b923ebbc14915bb08c32f9/packages/backend/src/open_payments/auth/middleware.ts#L141).

**Comment by sabineschaller** [comment] 2023-10-27 07:53
Yes please. Should we then also roll back the inclusion of the auth server url in the body of the public incoming payment? Like roll that back right away and get the auth server url from the header in the receiver service?

**Comment by njlie** [comment] 2023-10-30 16:47
On the heartbeat call, we discussed rolling back the `authServer` field in the unauthenticated `GET /incoming-payments` response body. We decided to keep it in the body, so it's more straightforward for the Open Payments client to retrieve and return that field and avoid some type breakage with having to return a header. Will still add the header so the endpoint behaves in a GNAP-y way.

**Closed** 2023-10-31 18:21 UTC
